// ==UserScript==
// @name         dulst.com的CardFighit Vanguard OverDulst文本替换汉化
// @namespace    http://tampermonkey.net/
// @version      0.6
// @description  通过将英文替换为中文的方法，汉化卡片战斗先导者OD的网页游戏
// @author       库X崔羊羊
// @match        https://dulst.com/overdulst
// @icon         https://www.google.com/s2/favicons?domain=dulst.com
// ==/UserScript==

//抄自→https://greasyfork.org/zh-CN/scripts/376441-soldout-2-%E6%96%87%E6%9C%AC%E6%9B%BF%E6%8D%A2
//我把includes去掉了↑
//他抄自→https://steamcn.com/forum.php?mod=viewthread&tid=418613
//我不懂JS，英语也不好，但是我喜欢VG！
//Stand up, The Vanguard！！！(๑•ㅂ•)و✧
//还在制作中ing...请关注群共享的更新

//【更新日志
//0.1:战斗以外的UI
//0.2:5国预组+刀剑预组+第1弹=0级单位、超触发和超触发指令的效果
//0.3:5国预组+刀剑预组+第1弹=完全防御和指令卡
//0.4:5国预组+刀剑预组+第1弹=卡名、种族、国家（39张卡名错误，翻译未生效，已反馈给作者）
//0.5:5国预组+刀剑预组+第1弹=1级和2级单位的效果
//0.6:第2弹=0级和1级单位、指令卡、前列触发
//0.7:第2弹=2级单位；

(function() {
    'use strict';

    const i18n = new Map([
        ['DISCLAIMER: Do NOT spread videos about this game nor send links to public groups... unless you want the game to get shut down again.', '免责声明：不要传播有关这个游戏的视频或发送链接到公共团体...除非你想让游戏再次关闭。'],
        ['Use your favorite Nation to win.', '用你最喜欢的国家赢得对战。'],
        ['Collect cards, build decks, and try out all sorts of potential combos!', '收集卡片,建立牌组,并尝试各种潜在的组合！'],
        ['Not Pay to Win \\(But Pray to the Gacha Gods\\)', '不是为了赢而付钱（而是祈祷神抽降临）'],
        ['All cards are collectible without real money purchases! You just need to grind out coins \\(fairly easily might I add\\) by playing against other people!', '所有的卡都是可以获得的,不用花真钱购买！你只需和别人对战就可以获得硬币！（相当容易获得）'],
        ['You disconnected from the Server. Please refresh your browser.', '您已断开与服务器的连接。请刷新浏览器。'],
        ['Search effect code by starting your search terms with code', '通过使用以下代码来来搜索效果文本'],
        ['At the end of the battle this unit boosted', '这个单位支援的战斗结束时'],
        ['if your Order Zone has a Set Order', '你的指令区中有设置指令卡的话'],
        ['and put this unit into your soul', '将这个单位放置到灵魂里'],
        ['Put this unit into your soul', '将这个单位放置到灵魂里'],
        ['put this unit into your soul', '将这个单位放置到灵魂里'],
        ['and Counter Charge', '计数回充'],
        ['1/Turn', '1回合1次'],
        ['and imprison it in your Prison', '收容到你的监狱'],
        ['if three or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有3张以上的话'],
        ['you draw a card', '你抽1张卡'],
        ['and if your World is', '如果你的世界卡的内容是'],
        ['if your World is', '如果你的世界卡的内容是'],
        ['If your World is', '如果你的世界卡的内容是'],
        ['search your deck for up to one World card', '从你的牌堆里探寻至多1张世界卡'],
        ['reveal it and put it into your hand', '公开后加入手牌'],
        ['and shuffle your deck', '然后牌堆洗切'],
        ['During the battle this unit attacked or boosted', '这个单位攻击或支援的战斗中'],
        ['When this unit attacks or boosts', '这个单位攻击或支援时'],
        ['and if you are in', '如果你处于'],
        ['If you are in', '如果你处于'],
        ['if you are in', '如果你处于'],
        ['Final Rush', '一气呵成之势'],
        ['put another rear-guard into your soul', '将你其他的1张后防者放置到灵魂里'],
        ['choose a card from your soul', '选择你的灵魂里的1张卡'],
        ['if your soul has five or more cards', '你的灵魂在5张以上的话'],
        ['and if your soul has ten or more cards', '你的灵魂在10张以上的话'],
        ['if your soul has ten or more cards', '你的灵魂在10张以上的话'],
        ['and when your opponent would call cards from their hand to \\(GC\\)', '对手要从手牌将卡CALL到G上之际'],
        ['when your opponent would call cards from their hand to \\(GC\\)', '对手要从手牌将卡CALL到G上之际'],
        ['they must call two or more at the same time', '不将2张以上同时CALL的话则不能CALL出场'],
        ['choose one of your other units in the same column as this unit', '选择你其他的1个与这个单位同纵列的单位'],
        ['When the attack this unit boosted hits a vanguard', '这个单位支援的攻击击中先导者时'],
        ['When the attack this unit boosted hits', '这个单位支援的攻击击中时'],
        ['retire this unit', '将这个单位退场'],
        ['search your deck for up to one card with the same card name as that unit', '从你的牌堆里探寻至多1张与那个单位同名的卡'],
        ['When your opponent\'s rear-guard is retired during your main phase', '你的主要阶段中对手的后防者退场时'],
        ['look at the top card of your deck', '看你的牌堆顶的1张卡'],
        ['and you may call a unit card from among them to', '你可以将查看的单位卡CALL到'],
        ['If you do not', '没有这么做的话'],
        ['If you do', '这么做的话'],
        ['and put the rest into your soul', '其余的卡放置到灵魂里'],
        ['put the rest into your soul', '其余的卡放置到灵魂里'],
        ['When this unit is rode upon by a unit with', '当这个单位被此卡RIDE→一个单位包含'],
        ['When this unit is rode upon by', '当这个单位被此卡RIDE→'],
        ['Cataclysmic Bullet of Dust Storm, Randor', '沙尘之凶弹 兰多尔'],
        ['When your opponent\'s rear-guard is retired during your main phase', '你的主要阶段中对手的后防者退场时'],
        ['and put it on the bottom of their deck', '放置到牌堆底'],
        ['look at two cards from the top of your deck', '看你的牌堆顶的2张卡'],
        ['choose a card from among them', '选择1张'],
        ['and put the rest on the bottom of your deck in any order', '其余的卡按希望的顺序放置到牌堆底'],
        ['and put the rest on the bottom of your deck', '其余的卡放置到牌堆底'],
        ['and draw two cards', '抽2张卡'],
        ['Draw two cards', '抽2张卡'],
        ['draw two cards', '抽2张卡'],
        ['choose up to one order card from your hand', '选择你的手牌中的至多1张指令卡'],
        ['and if you did not discard', '没有舍弃的话'],
        ['choose two cards from your hand', '选择手牌中的的2张卡'],
        ['and discard them', '舍弃'],
        ['Blaze Maiden, Reiyu', '焰之巫女 蕾尤'],
        ['During the battle this unit attacked', '这个单位攻击的战斗中'],
        ['During the battle this unit attacks', '这个单位攻击的战斗中'],
        ['call it to your back row center', 'CALL到中央后列的'],
        ['and if your vanguard is', '如果你的先导者是'],
        ['If your vanguard is', '如果你的先导者是'],
        ['if your vanguard is', '如果你的先导者是'],
        ['Diabolos, "Violence" Bruce', '魔惧会 “暴虐” 布鲁斯'],
        ['Knight of Heavenly Spear, Rooks', '天枪的骑士 勒克斯'],
        ['reveal two grade 3 cards from your hand', '将手牌中的2张等级3的卡公开'],
        ['you may reveal the top card of your deck', '将你的牌堆顶的1张卡公开'],
        ['reveal the top card of your deck', '将你的牌堆顶的1张卡公开'],
        ['and you may call it to \\(RC\\) if it is a unit card', '那张卡是单位卡的话,你可以将那张卡CALL到R上'],
        ['if it is a unit card', '←如果那张卡是单位卡'],
        ['and put it into your drop if it isn\'t', '不是的话,放置到弃牌区'],
        ['choose one of your grade 3 vanguards', '选择你的1张等级3的先导者'],
        ['Sylvan Horned Beast, Lattice', '树角兽 拉提斯'],
        ['If it is a grade 2 or less unit card', '那张卡是等级2以下的单位卡的话'],
        ['and discard it if it isn\'t', '不是的话,将那张卡舍弃'],
        ['and if it isn\'t', '不是的话'],
        ['if it isn\'t', '不是的话'],
        ['and put it into your soul', '放置到你的灵魂里'],
        ['put it into your soul', '放置到你的灵魂里'],
        ['Back Row RC', '后列的R'],
        ['This represents a Shadow Army token', '这是表示夜影兵衍生物的卡'],
        ['and cannot be put in a deck', '不能投入到卡组中'],
        ['If one or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有1张以上的话'],
        ['if one or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有1张以上的话'],
        ['and put it on the top of your deck or into your soul', '放置到牌堆顶或灵魂里'],
        ['put it on the top of your deck', '放置到牌堆顶'],
        ['and put it on the top or bottom of your deck', '放置到牌堆顶或牌堆底'],
        ['If you put it on the bottom of your deck', '放置到牌堆底了的话'],
        ['If you played an order this turn', '这个回合中你使用过指令卡的话'],
        ['If two or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有2张以上的话'],
        ['When a World is put into your order zone', '世界卡被放置到你的指令区时'],
        ['When this card is discarded from hand during your turn', '你的回合中这张卡从手牌舍弃时'],
        ['if you have a Set Order in your Order Zone', '你的指令区有设置指令卡的话'],
        ['and call this card to', '将这张卡CALL到'],
        ['if an opponent\'s card is imprisoned in your Prison', '被收容在你的监狱的对手的卡有1张以上的话'],
        ['Master of Gravity, Baromagnes', '重力的支配者 磁力重压'],
        ['put a card from your hand into your soul', '将手牌中的1张卡放置到灵魂里'],
        ['and if this unit', '如果这个单位'],
        ['this turn by a card effect', '于这个回合中被卡片的效果'],
        ['At the end of the battle this unit attacked', '这个单位攻击的战斗结束时'],
        ['If you Soul Charge this turn', '这个回合中你进行过灵魂填充的话'],
        ['Heavy Artillery of Dust Storm, Eugene', '沙尘之重炮 尤金'],
        ['choose up to one card from your drop', '选择你的弃牌区中的至多1张卡'],
        ['if your opponent has two or less rear-guards', '对手的后防者在2张以下的话'],
        ['overDress', '超限舞装'],
        ['When this unit intercepts', '这个单位截击时'],
        ['choose one of your opponent\'s grade 2 or greater rear-guards', '选择对手的1张等级2以上的后防者'],
        ['look at three cards from the top of your deck', '看你牌堆顶的3张卡'],
        ['and put them on the top of your deck in any order', '按希望的顺序放置到牌堆顶'],
        ['choose two of your units', '选择你的2个单位'],
        ['you may discard three cards from the top of your deck', '你可以将你的牌堆顶的3张卡舍弃'],
        ['the next time when you would play an order as', '你下一次将指令卡使用通过→'],
        ['you do not have to pay all Soul Blast from that cost', '你可以不支付那个费用中所有的灵魂爆发'],
        ['search your deck for up to one Prison card', '从你的牌堆里探寻至多1张监狱卡'],
        ['choose a grade 2 or less card from your drop', '选择你的弃牌区中的1张等级2以下的卡'],
        ['choose up to one normal order from your drop', '选择你的弃牌区中的至多1张普通指令卡'],
        ['and it gets this unit\'s', '它获得这个单位的'],
        ['Increase its \\[Power\\] at that time', '增加结算这个能力时这个单位的力量'],
        ['Increase its', '增加它的'],
        ['at that time', '在那时'],
        ['When this unit in the', '当这个单位处于'],
        ['state attacks a vanguard', '攻击先导者时'],
        ['Chakrabarthi Divine Dragon, Nirvana', '天轮圣龙 涅槃'],
        ['put a rear-guard into your soul', '将你的1张后防者放置到灵魂里'],
        ['When this unit is put into your', '当这个单位被放置到'],
        ['Apex Ruler, Bastion', '顶峰天帝 巴斯提昂'],
        ['reveal three grade 3 cards from your hand', '将手牌中的3张等级3的卡公开'],
        ['if you have three or more grade 3 units', '你的等级3的单位有3个以上的话'],
        ['If you have four or more other rear-guards', '你其他的后防者在4张以上的话'],
        ['Sylvan Horned Beast King, Magnolia', '树角兽王 马格诺利亚'],
        ['When this unit attacks a vanguard', '这个单位攻击先导者时'],
        ['When this unit attacks', '这个单位攻击时'],
        ['your opponent chooses a card from their hand', '对手选择他自己的手牌中的1张卡'],
        ['and imprisons it in your Prison', '收容到你的监狱'],
        ['reveal it and put it to your hand', '公开后加入手牌'],
        ['Retire this unit', '将这个单位退场'],
        ['and call up to three Shadow Army tokens to \\(RC\\)', '将至多3张夜影兵衍生物CALL到R上'],
        ['and when this unit would attack', '这个单位进行攻击之际'],
        ['when this unit would attack', '这个单位进行攻击之际'],
        ['when this unit would attack', '这个单位进行攻击之际'],
        ['it battles all of the units in one of your opponent\'s columns', '与对手的一个纵列上的所有的单位进行战斗'],
        ['Choose one of your opponent\'s front row rear-guards', '选择前列的对手的1张后防者'],
        ['and perform all of the following according to the number of cards in your soul', '根据你的灵魂里的卡的张数发动以下全部的效果'],
        ['and if you have 5 or more cards in your damage zone', '你的伤害区中的卡有5张以上的话'],
        ['•2 or more', '•2张以上'],
        ['•3 or more', '•3张以上'],
        ['•4 or more', '•4张以上'],
        ['•5 or more', '•5张以上'],
        ['•10 or more', '•10张以上'],
        ['•15 or more', '•15张以上'],
        ['this unit gets "Boost", and', '这个单位获得『支援』的技能，并'],
        ['This unit gets', '这个单位获得'],
        ['Both you and your opponent put all of your own rear-guards into your souls', '你和对手分别将他自己所有的后防者放置到各自的灵魂里'],
        ['Choose up to two cards from your soul', '选择你的灵魂里的至多2张卡'],
        ['call them to \\(RC\\)', 'CALL到R上'],
        ['and those units get', '那些单位获得'],
        ['put one of your other rear-guards into your soul', '将你其他的1张后防者放置到灵魂里'],
        ['If your opponent\'s rear-guard was retired this turn', '这个回合中对手曾有后防者退场过的话'],
        ['look at the same number of cards from the top of your deck as the number of your opponent\'s open \\(RC\\)', '看你的牌堆顶的数量与对手的不存在单位的R的个数相同的卡'],
        ['choose any number of unit cards from among them', '选择你希望的张数的单位卡'],
        ['call them to \\(RC\\)', 'CALL到R上'],
        ['When your vanguard attacks', '你的先导者攻击时'],
        ['or a grade 3 or less unit in the', '或等级3以下的后防者处于'],
        ['For players who participated in the overDulst Beta', '赠与参加超限舞装内测的玩家'],
        ['choose up to two unit cards from among them', '选择至多2张单位卡'],
        ['and put the rest on the top of your deck in any order', '其余的卡按希望的顺序放置到牌堆顶'],
        ['If you have a vanguard with', '如果你的先导者拥有'],
        ['if you have a vanguard with', '如果你的先导者拥有'],
        ['in its card name', '在它的卡名里'],
        ['when this unit would be retired for your card\'s cost', '由于你的卡片的费用要将这个单位退场之际'],
        ['you may retire it as two rear-guards', '这个单位可以当做2张的份量'],
        ['Put this unit into your damage zone', '将这张卡放置到伤害区'],
        ['choose a face up grade 3 card from your damage zone', '选择你的伤害区中的1张正面表示的等级3的卡'],
        ['increase of the trigger effects revealed by your drive check gets', '因你的攻击判定判出的触发效果增加时再'],
        ['Blaster Dark', '暗黑狂风'],
        ['Blaster', '狂风'],
        ['At the end of that turn', '这个回合结束时'],
        ['retire that called unit', '将被CALL出场的那个单位退场'],
        ['Put it on the top of the deck if you did not call', '没有CALL出场的话放置回牌堆顶'],
        ['When this unit boosts a vanguard', '这个单位支援先导者时'],
        ['Triple Drive', '三判'],
        ['Drive check three times', '能够进行3次攻击判定'],
        ['choose three of your front row units', '选择前列的你的3个单位'],
        ['The \\[Power\\] gained from this unit\'s boost will be lost', '通过这个单位支援给予的力量增加会不再有效'],
        ['When this unit boosts a rear-guard', '这个单位支援后防者时'],
        ['if you persona rode this turn', '这个回合中你进行了人格RIDE的话'],
        ['and your opponent cannot call grade 1 or greater cards from their hand to \\(GC\\) until end of that battle', '这次战斗中,对手不能将等级1以上的卡从手牌CALL到G上'],
        ['if you have five or more cards in your soul', '你的灵魂里的卡有5张以上的话'],
        ['This card cannot be ridden', '这张卡不能RIDE'],
        ['called or moved to the front row', 'CALL或移动将这张卡放置到前列'],
        ['When you would move or swap rear-guards during your main phase', '你在主要阶段中将后防者移动或交换位置之际'],
        ['you can also move it within the same row', '也可以在横列间移动或交换位置'],
        ['Your units in front of this unit cannot be chosen by your opponent\'s effects', '这个单位前方的你的单位不会被对手的效果选择'],
        ['Note:', '注意：'],
        ['Currently lets units move anywhere on the board instead of allowing movement by row.', '目前允许单位在圆阵上任意移动,而不是纵横移动'],
        ['the next time you would', '你下一次通过'],
        ['an order and play it this turn', '将指令卡使用之际'],
        ['reduce that cost by', '那个费用减少'],
        ['Reduce from the total cost', '在合计的费用中减少'],
        ['Does not Counter Charge even if it becomes negative', '但是即使减到负数也不能计数回充'],
        ['bind this unit', '将这个单位封锁'],
        ['choose an order card from your bind zone', '选择你的封锁区中的1张指令卡'],
        ['you may put all cards from your bind zone into the drop', '你可以将你的封锁区中所有的卡放置到弃牌区'],
        ['until end of turn for each card put', '←放置的卡每有1张,直到回合结束'],
        ['you may discard the top five cards of your deck', '你可以将你的牌堆顶的5张卡舍弃'],
        ['until end of that battle for each of your rear-guards', '←你的后防者每有1张,在这次战斗中'],
        ['Beta Promo', '内测奖励'],
        ['Granted to the top 2 players of the first overDulst tournament!!', '授予第1届overDulst锦标赛的前两名选手！！'],
        ['if you have another unit with', '如果你有其他的单位含有'],
        ['Toushirou', '藤四郎'],
        ['When this unit boosts a', '当这个单位支援'],
        ['you may have this unit get', '你可以使这个单位获得'],
        ['at the end of that battle', '这次战斗结束时'],
        ['retire all of your rear-guards in the same column as this unit', '将与这个单位同纵列的你所有的后防者退场'],
        ['Discard a set order card from your hand', '将手牌中的1张设置指令卡舍弃'],
        ['retire a Shadow Army token', '将1张夜影兵衍生物退场'],
        ['If one or less of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡在1张以下的话'],
        ['choose a unit card from your opponent\'s drop', '选择对手的弃牌区中的1张单位卡'],
        ['During the battle this unit boosted a vanguard', '这个单位支援先导者的战斗中'],
        ['During the battle this unit boosted a grade 0', '这个单位支援等级0的单位的战斗中'],
        ['During the battle this unit boosted', '这个单位支援的战斗中'],
        ['if two or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有2张以上的话'],
        ['If you have a Set Order in your order zone', '你的指令区有设置指令卡的话'],
        ['if five or more of your opponent\'s cards are imprisoned in your Prison', '被收容在你的监狱的对手的卡有5张以上的话'],
        ['Blaze Maiden, Rino', '焰之巫女 莉诺'],
        ['is on your \\(VC\\) or \\(RC\\)', '存在于你的V或R上'],
        ['on your \\(VC\\) or \\(RC\\)', '在你的V或R上'],
        ['Dragon Knight, Nehalem', '龙骑士 尼海连'],
        ['search your deck for up to one grade 1 card', '从你的牌堆里探寻至多1张等级1的卡'],
        ['When your vanguard\'s attack hits', '你的先导者的攻击击中时'],
        ['choose one of your opponent\'s rear-guards in the same column as this unit', '选择与这个单位同纵列的对手的1张后防者'],
        ['you may put this card into your soul', '你可以将这张卡放置到灵魂里'],
        ['When the attack this unit boosted a vanguard hits', '这个单位支援先导者的攻击击中时'],
        ['and perform one of the following', '从以下效果中将1项执行'],
        ['When your unit with the', '当你的单位具备'],
        ['ability attacks', '能力攻击时'],
        ['choose one of your units with the', '选择你的1个单位具备'],
        ['choose one of your units with', '选择你的1个单位含有'],
        ['choose one of your opponent\'s back row rear-guards', '选择后列的对手的1张后防者'],
        ['and can only be called to the back row center \\(RC\\)', '只能CALL到中央后列的圆阵上'],
        ['If your opponent\'s vanguard is grade 3 or greater', '对手有等级3以上的先导者的话'],
        ['if your opponent\'s vanguard is grade 3', '对手有等级3的先导者的话'],
        ['choose up to one card with the same grade as your vanguard or lower from your drop', '选择你的弃牌区中的至多1张等级在你的先导者的等级以下的卡'],
        ['choose up to two cards instead of one', '不选择1张而是可以选择至多2张'],
        ['Bind this card', '将这张卡封锁'],
        ['choose up to two order cards from your drop', '选择你的弃牌区中的至多2张指令卡'],
        ['and put them into your hand', '加入手牌'],
        ['for every five cards in your drop', '←当你的弃牌区中的卡每有5张'],
        ['and if your drop has fifteen or more cards', '你的弃牌区中的卡在15张以上的话'],
        ['all of your back row rear-guards get', '后列的你所有的后防者获得'],
        ['you cannot move rear-guards to other \\(RC\\)', '你的后防者不能移动到其他的R上'],
        ['and they cannot boost', '并且他们不能支援'],
        ['Choose one of your opponent\'s attacking units', '选择对手的1个正在攻击的单位'],
        ['until end of turn for each of your opponent\'s cards imprisoned in your Prison', '这个回合中←当被收容在你的监狱的对手的卡每有1张'],
        ['It does not retire even if its \\[Power\\] becomes negative', '单位的力量变为负数也不会退场'],
        ['If your opponent\'s hand has four or more cards', '对手的手牌在4张以上的话'],
        ['you choose one of your units', '你选择你自己的1个单位'],
        ['Exchange for Promo cards in', '兑换奖品卡在→'],
        ['Discard three cards from the top of your deck', '将你的牌堆顶的3张卡舍弃'],
        ['token to \\(RC\\)', '衍生物到R上'],
        ['Shadow Army has \\[Power\\]15000 and Boost', '夜影兵具备15000力量与支援的技能'],
        ['If you have a rear-guard with the', '如果你有你有后防者具备'],
        ['When all of your units would attack', '你所有的单位在将要攻击之际'],
        ['they may attack your opponent\'s back row rear-guard', '可以攻击后列的对手的后防者'],
        ['Perform all of the effects below according to the number of your grade 3 units', '根据你的等级3的单位的个数执行以下所有的效果'],
        ['If you have three or more grade 3 units', '你的等级3的单位有3个以上的话'],
        ['Including GC', '也包含防卫者圆阵上的单位'],
        ['and you may put it into your hand', '你可以将它加入手牌'],
        ['Choose one of any player\'s rear-guards', '选择任意玩家的1张后防者'],
        ['choose up to one card with the same grade as that card from your drop', '选择你的弃牌区中的至多1张等级与被退场的卡的等级相同的卡'],
        ['you may choose up to two instead of one to call', '不选择1张而是选择至多2张单位卡CALL到R上'],
        ['discard a card with the', '舍弃一张卡具备→'],
        ['ability from your hand', '能力从你手牌'],
        ['All of your rear-guards get', '你所有的后防者获得'],
        ['When your vanguard is placed', '你的先导者登场时'],
        ['Front Row RC', '前列的R'],
        ['your opponent cannot intercept', '对手不能截击'],
        ['If you have three or more other rear-guards', '你其他的后防者有3张以上的话'],
        ['it battles all of your opponent\'s units in a column', '与对手的一个纵列上的所有的单位进行战斗'],
        ['choose up to one card from your soul', '选择你的灵魂里的至多1张卡'],
        ['and call it to an open \\(RC\\)', 'CALL到不存在单位的R上'],
        ['and put this card into drop', '将这张卡放置到弃牌区'],
        ['that unit can attack from the back row', '那个单位可以从后列攻击'],
        ['and gets', '并获得'],
        ['When this unit is chosen by your vanguard\'s effect', '这个单位被你的先导者的效果选择时'],
        ['if your damage zone has no face up cards', '你的伤害区中没有正面表示的卡的话'],
        ['choose up to two cards from among them', '看你牌堆顶的2张卡,选择至多2张'],
        ['put them on the top of your deck in any order', '按希望的顺序放置到牌堆顶'],
        ['retire another rear-guard', '将你其他的1张后防者退场'],
        ['look at five cards from the top of your deck', '看你的牌堆顶的5张卡'],
        ['choose up to one grade 1 or less unit card from among them', '选择至多1张等级1以下的单位卡'],
        ['if your rear-guard was retired this turn', '这个回合中你的后防者曾退场过的话'],
        ['an order this turn', '指令卡在这个回合中'],
        ['bind an order card from drop', '将你的弃牌区中的1张指令卡封锁'],
        ['call this card to an open \\(RC\\)', '将这张卡CALL到不存在单位的R上'],
        ['this unit battles all of your opponent\'s front row units', '与前列的对手所有的单位进行战'],
        ['This unit can intercept from the back row.', '这个单位也可以从后列截击'],
        ['If you have a total of three or more order cards in your drop and bind zone', '你的弃牌区和封锁区中的指令卡合计有3张以上的话'],
        ['until end of battle for each of your other rear-guards', '←当你其他的后防者每有1张,在这次战斗中'],
        ['When your opponent\'s card imprisoned in your Prison is placed on \\(RC\\)', '被收容在你的监狱的对手的卡登场到R时'],
        ['and it cannot be hit by a grade 2 or lower unit\'s attack until end of that battle', '这次战斗中,那个单位不会被等级2以下的单位的攻击击中'],
        ['choose up to one World card from among them', '选择至多1张世界卡'],
        ['At the end of each turn', '每个回合结束时'],
        ['both you and your opponent choose one of your own rear-guards', '你和对手分别选择他自己的1张后防者'],
        ['The turn fighter chooses the unit to retire first', '需要双方玩家同时选择的场合,以回合玩家先选择、非回合玩家再选择的方式执行'],
        ['choose one of your opponent\'s imprisoned cards in your Prison', '选择1张被收容在你的监狱的对手的卡'],
        ['and put it into their drop', '放置到对手的弃牌区'],
        ['if this unit was boosted', '这个单位正在被支援的话'],
        ['At the end of the battle your', '当战斗结束于你的'],
        ['attacked a vanguard', '攻击先导者'],
        ['this card on your', '这张卡在你的'],
        ['on \\(RC\\) as \\[Stand\\]', '←处于R上,并[重置]'],
        ['If this unit is in the', '如果这个单位处于'],
        ['Active on opponent\'s turn too', '在对手的回合中也有效'],
        ['At the start of your battle phase', '你的战斗阶段开始时'],
        ['if your opponent has one or less rear-guards', '对手的后防者在1张以下的话'],
        ['call this card to \\(RC\\)', '将这张卡CALL到R上'],
        ['choose one of your opponent\'s grade 2 or less rear-guards', '选择对手的1张等级2以下的后防者'],
        ['choose a grade 0 card from your drop', '选择你的弃牌区中的1张等级0的卡'],
        ['choose one of your grade 0 units', '选择你的1个等级0的单位'],
        ['and you may move it to your opponent\'s open front row \\(RC\\)', '你可以选择对手的1张后防者'],
        ['Automatically places to Open RC \\(Prioritizes enemy\'s left circle', '移动到不存在单位的对手的前列的R上'],
        ['When your grade 0 unit attacks', '你的等级0的单位攻击时'],
        ['this unit and the unit that attacked get', '这个回合中,那个攻击的单位和这个单位获得'],
        ['and if your opponent\'s front row has a rear-guard', '前列有对手的后防者的话'],
        ['this unit cannot attack the vanguard.', '这个单位不能攻击先导者'],
        ['you choose up to two unit cards from your opponent\'s drop', '你选择对手的弃牌区中的最多2张单位卡'],
        ['and imprison them in your Prison', '收容到你的监狱'],
        ['call a grade 1 from your hand to \\(RC\\)', '将手牌中的1张等级1的卡CALL到R上'],
        ['and the unit called for this cost gets', '由于这个费用而被CALL出场的单位获得'],
        ['for each of this unit\'s', '←当这个单位每有1张'],
        ['When the attack of this unit in the', '当这个单位攻击时处于'],
        ['When your drive check reveals a trigger unit', '你的攻击判定将触发单位卡判出时'],
        ['When this unit\'s attack hits a vanguard', '这个单位的攻击击中先导者时'],
        ['When this unit\'s attack hits', '这个单位的攻击击中时'],
        ['choose one of your other rear-guards', '选择你其他的1张后防者'],
        ['When this unit is placed on \\(RC\\) from hand', '这个单位从手牌登场到R时'],
        ['When this unit is placed on \\(RC\\)', '这个单位登场到R时'],
        ['When this unit is placed on', '当这个单位登场到'],
        ['When this unit boosts', '这个单位支援时'],
        ['This unit cannot be chosen by your opponent\'s card effects', '这个单位不会被对手的卡片的效果选择'],
        ['and Soul Charge', '灵魂填充'],
        ['Soul Charge', '灵魂填充'],
        ['Soul Blast', '灵魂爆发'],
        ['Play this with', '支付'],
        ['Play with this', '支付'],
        ['COST', '支付'],
        ['When this unit is rode upon', '这个单位被RIDE时'],
        ['if you went second', '你是后攻的话'],
        ['and draw a card', '并抽1张卡'],
        ['draw a card', '抽1张卡'],
        ['Additional Effect', '追加效果'],
        ['and they get', '并使它们获得'],
        ['and that unit gets', '并使该单位获得'],
        ['that unit gets', '该单位获得'],
        ['and it gets', '并使它获得'],
        ['and this unit gets', '这个单位获得'],
        ['this unit gets', '这个单位获得'],
        ['it gets', '它获得'],
        ['and until end of turn', '直到回合结束'],
        ['Choose one of your vanguards, and', '选择你的1张先导者,并'],
        ['Choose one of your vanguards', '选择你的1张先导者'],
        ['Choose one of your vanguard', '选择你的1张先导者'],
        ['choose one of your vanguards', '选择你的1张先导者'],
        ['Stand', '重置'],
        ['and heal it', '回复'],
        [' it!', '它!'],
        ['You get', '你获得'],
        ['During your turn', '你的回合中'],
        ['and this unit and all of your vanguards get', '将当前存在于场上的你所有的先导者和这个单位获得'],
        ['all of your vanguards get', '你所有的先导者获得'],
        ['Critical', '暴击'],
        ['until end of this fight', '直到游戏结束'],
        ['Double the', '翻倍'],
        ['of all of your front row units', '给当前存在于前列的你所有的单位'],
        ['Increase to double its', '翻倍它的'],
        ['when activated', '在触发时'],
        ['you also perform drive checks for the battles your rear-guards attack', '你的后防者攻击的战斗中也进行攻击判定'],
        ['If your damage zone has more cards than your opponent\'s', '你的伤害区中的卡的张数在对手的伤害区中的卡的张数以上的话'],
        ['choose a card from your damage zone', '选择你的伤害区中的1张卡'],
        ['100 Million', '1亿'],
        ['and all of your front row units get', '当前存在于前列的你所有的单位的获得'],
        ['All of your front row units get', '当前存在于前列的你所有的单位'],
        ['all of your front row units get', '当前存在于前列的你所有的单位'],
        ['During this turn', '这个回合中'],
        ['all your units get', '当前存在于场上的你所有的单位获得'],
        ['When played', '施放时效果'],
        ['Resolve this effect when played as an order', '当指令卡使用时发动效果'],
        ['all your units get', '你的所有单位都会获得此效果'],
        ['If your soul has five or more cards', '你的灵魂在5张以上的话'],
        ['choose one of your units', '选择你的1个单位'],
        ['Choose a card with grade equal to or less than your vanguard from your drop', '选择你的弃牌区中的1张等级在你的先导者的等级以下的卡'],
        ['and call them to', '并将它们CALL到'],
        ['and call it to \\(RC\\)', '并将它CALL到R上'],
        ['and call it to', '并将它CALL到'],
        ['call it to a back row \\(RC\\)', 'CALL到后列的R上'],
        ['call it to \\(RC\\)', '将它CALL到R上'],
        ['call it to', '将它CALL到'],
        ['If your damage zone has three or more cards', '你的伤害区中的卡有3张以上的话'],
        ['Choose one of your rear-guards that is not being attacked', '选择你的1张没有正在被攻击的后防者'],
        ['Choose one of your rear-guards', '选择你的1张后防者'],
        ['choose one of your rear-guards', '选择你的1张后防者'],
        ['and return it to your hand', '返回手牌'],
        ['Choose one of your opponent\'s vanguards', '选择对手的1张先导者'],
        ['Choose one of your opponent\'s rear-guards for each Counter Blast paid for this cost', '由于这个费用支付的计数爆发1每有1张,选择对手的1张后防者'],
        ['choose one of your opponent\'s rear-guards', '选择对手的1张后防者'],
        ['Counter Blast one or more cards', '使用1张或以上的卡进行计数爆发'],
        ['Counter Blast', '计数爆发'],
        ['Choose one of your units', '选择你的1个单位'],
        ['That called unit cannot be moved to another \\(RC\\) until end of turn', '这个回合中,那个CALL出场的单位不能移动到其他的R上'],
        ['until end of turn', '直到回合结束'],
        ['Until end of turn', '直到回合结束'],
        ['until the end of the turn', '直到回合结束'],
        ['Then', '这之后'],
        ['for every five cards in your soul', '←当你的灵魂里的卡每有5张'],
        ['If your soul has ten or more cards', '你的灵魂在10张以上的话'],
        ['draw a card', '抽1张卡'],
        ['Draw a card', '抽1张卡'],
        ['retire two rear-guards', '将你的2张后防者退场'],
        ['put this card into your soul, and', '将这张卡放置到灵魂里,并'],
        ['put this card into your soul', '将这张卡放置到灵魂里'],
        ['Counter Charge', '计数回充'],
        ['Choose a', '选择1张'],
        ['from your drop', '←于你的弃牌区里'],
        ['put it into your hand if it is an order card or a grade 3', '那张卡是指令卡或等级3的卡的话,加入手牌'],
        ['and put it into your hand', '加入手牌'],
        ['put it into your hand', '加入手牌'],
        ['If you have three or more back row rear-guards', '你后列的后防者有3张以上的话'],
        ['instead of one to', '而不是选择1张'],
        ['instead of', '而不是'],
        ['and retire them', '退场'],
        ['and retire it', '退场'],
        ['retire it', '退场'],
        ['If you have three or more units', '你的单位有3个以上的话'],
        ['Choose one of your opponent\'s rear-guards', '选择对手的1张后防者'],
        ['Your opponent puts all of their rear-guards in the same column as that rear-guard on the bottom of their deck in any order', '对手将与那张后防者同纵列的他自己所有的后防者按希望的顺序放置到牌堆底'],
        ['Buggy', '有bug'],
        ['Look at four cards from the top of your deck', '看你牌堆顶的4张卡'],
        ['choose up to one unit card from among them', '选择至多1张单位卡'],
        ['and discard the rest', '将其余的卡舍弃'],
        ['If during', '如果现在处于'],
        ['Alchemagic', '魔合成'],
        ['call up to two cards', '选择至多2张单位卡'],
        ['and all of this order\'s called units get', '由于这张指令卡而被CALL出场的所有单位'],
        ['Mysterious Rain Spiritualist, Zorga', '怪雨的降灵术师 佐尔加'],
        ['choose three of your units', '选择你的3个单位'],
        ['one of your units', '将你的1个单位横置'],
        ['to play this card', '来发动此卡'],
        ['When this card is put in the order zone', '这张卡被放置到指令区时'],
        ['When this card is put into the Order Zone', '这张卡被放置到指令区时'],
        ['When this card is put into order zone', '这张卡被放置到指令区时'],
        ['Order Zone', '指令区'],
        ['When your opponent can normal call a rear-guard', '对手在可以将后防者通常CALL出场的时段'],
        ['they can perform the following', '对手可以从以下效果中将1项执行'],
        ['If they do so', '这样做了的话'],
        ['they choose one of their imprisoned cards', '选择被收容的他自己的1张卡'],
        ['they choose two of their imprisoned cards', '选择被收容的他自己的2张卡'],
        ['Click your VC to Prison Break', '带领你的先导者越狱吧'],
        ['If your order zone only has World cards', '你的指令区中没有世界卡以外的设置指令卡的话'],
        ['the following effects are active according to the number of cards in your order zone', '根据你的指令区中的卡的张数生效以下全部的效果'],
        ['Your World becomes', '你的世界卡的内容变为'],
        ['Abyssal Dark Night', '深渊黑夜'],
        ['Dark Night', '黑夜'],
        ['2 or more cards', '2张以上'],
        ['choose one of your opponent\'s front row rear-guards', '选择前列的对手的1张后防者'],
        ['Sentinel', '守护者'],
        ['When this unit is put on', '当这个单位被放置到'],
        ['and it cannot be hit until end of that battle', '这次战斗中,不会被击中'],
        ['and until end of that battle', '在这次战斗中'],
        ['until end of that battle', '在这次战斗中'],
        ['If your hand has two or more cards', '你的手牌中的卡在2张以上的话'],
        ['choose a card from your hand', '选择手牌中的1张卡'],
        ['discard a card from your hand', '将手牌中的1张卡舍弃'],
        ['and discard it', '舍弃'],
        ['discard it', '舍弃'],
        ['search your deck for up to one', '从你的牌堆里探寻至多1张'],
        ['Select 1 card', '选择1张卡'],
        ['1 card', '1张'],
        ['Aegismare Dragon', '神盾幻马龙'],
        ['Acrobat Presenter', '杂技主持人'],
        ['Alert Guard Gunner', '警戒守卫枪手'],
        ['Uncanny Burning', '怪异燃烧'],
        ['Violate Dragon', '违抗龙'],
        ['Vairina Arcs', '瓦尔里纳·弓弧'],
        ['Vairina Valiente', '瓦尔里纳·勇气'],
        ['Vairina', '瓦尔里纳'],
        ['Eminence Jaboberus', '出众三头巨犬'],
        ['Electro Spartan', '电光斯巴达'],
        ['Autonomic Caution', '自律警报器'],
        ['Grapple External', '搏击外来者'],
        ['Granaroad Fairtigar', '暗红·化虎'],
        ['Ghost Chase', '幽灵追猎'],
        ['Conduct Spark Dragon', '电光导流龙'],
        ['Sunburst Evolution', '骤阳之进化'],
        ['Sunrise Egg', '拂晓之蛋'],
        ['Sunlight Punishment', '阳光之惩戒'],
        ['Shadow Leak Magician', '渗影奇术师'],
        ['Steam Artist Pithana', '蒸汽艺术家 皮坦纳'],
        ['Steam Gunner Brody', '蒸汽枪手 布罗迪'],
        ['Steam Scara Mal-Nigal', '蒸汽测量者 玛尔尼加尔'],
        ['Steam Detective Uvaritt', '蒸汽侦探 乌巴里特'],
        ['Steam Battler Gungnram', '蒸汽战士 贡古努拉姆'],
        ['Security Patroller', '安保巡逻员'],
        ['Selfish Engraver', '自私雕刻师'],
        ['Dark Strain Dragon', '暗黑重压龙'],
        ['Direful Doll Simone', '恐怖人偶 希蒙涅'],
        ['Tartarus Beatscram', '地狱猛打并列争球'],
        ['Twin Buckler Dragon', '双盾龙'],
        ['Diabolos \'Violence\' Bruce', '魔惧会 “暴虐” 布鲁斯'],
        ['Diabolos \'Bad\' Steve', '魔惧会 “恶童” 史蒂夫'],
        ['Diabolos \'Anger\' Richard', '魔惧会 “愤怒” 理查德'],
        ['Diabolos \'Innocent\' Matt', '魔惧会 “无垢” 玛特'],
        ['Diabolos Officer Gillian', '魔惧会指挥 基里安'],
        ['Diabolos Girls Arianna', '魔惧会女孩 雅莉安娜'],
        ['Diabolos Girls Maimai', '魔惧会女孩 麦麦'],
        ['Diabolos Boys Eden', '魔惧会男孩 伊登'],
        ['Diabolos Boys Jake', '魔惧会男孩 杰克'],
        ['Deep Soniker', '深度音速'],
        ['Divine Sister Tartine', '神圣修女 果酱面包片'],
        ['Divine Sister Pastelitos', '神圣修女 酥皮馅饼'],
        ['Divine Sister Faciata', '神圣修女 珐希亚塔'],
        ['Divine Sister Lepisto', '神圣修女 莱比斯托'],
        ['Dragritter Alwalith', '龙族骑士 阿尔瓦利斯'],
        ['Dragritter Zafar', '龙族骑士 扎法尔'],
        ['Dragritter Dabbaax', '龙族骑士 达巴弗'],
        ['Trickstar', '托里科斯塔'],
        ['Nikkari Aoe', '笑面青江'],
        ['Vital Leaver', '致命掠夺'],
        ['Hydrolic Ram Dragon', '液压撞击龙'],
        ['Huckle Hustle', '喧闹砍伐'],
        ['Brothers\' Soul', '兄弟会之魂'],
        ['Platinum Wolf', '白金之狼'],
        ['Planar Prevent Dragon', '预防气息龙'],
        ['Flinty Slasher', '燧石斩击'],
        ['Protobulb Dragon', '原始阀门龙'],
        ['Painkiller Angel', '止痛天使'],
        ['Heshikiri Hasebe', '压切长谷部'],
        ['Hopeful Testode', '希望龟甲阵'],
        ['Useful Recharger', '有益再充能者'],
        ['Recusal Hate Dragon', '憎恶回避龙'],
        ['Looting Petal Stomalia', '根植花瓣 斯特玛利亚'],
        ['Lost Child of Attachment', '留恋的迷路人'],
        ['Dark Pilgrimage', '暗淡游灵'],
        ['White Light Dragon Parasolace', '白光龙 慰藉副栉龙'],
        ['White Crow Sorcerer Taxus', '白乌的魔术师 红豆杉'],
        ['White Fang Witch Disma', '白牙之魔女 松叶菊'],
        ['Jeweled Combination Jewelion', '宝珠合体 玉石式'],
        ['Grief Despair and Rejection', '悲叹与绝望,以及拒绝'],
        ['Spurring Maiden Ellenia', '鞭挞的少女 伊蕾尼娅'],
        ['Icicle Ein Aizer', '冰冥之贵公子 艾扎'],
        ['Hakata Toushirou', '博多藤四郎'],
        ['Fudou Yukimitsu', '不动行光'],
        ['Psychic Prima Miranda', '超动之舞姬 米兰达'],
        ['Hyperspeed Robo Chevalstud', '超速机器人 良种骏马'],
        ['Yamatonokami Yasusada', '大和守安定'],
        ['Big Snake Witch Solaria', '大蛇之魔女 美蛛花'],
        ['Lightning Thief Monster Jabattail', '盗电怪兽 贾巴特尔'],
        ['Crawl you \'Insects\'!', '在地上爬行吧,“下等生物”！'],
        ['Lightning Barrier Emergency Deployment!', '电光防壁,紧急展开'],
        ['Electrode Monster Adapton', '电极怪兽 阿达仆通'],
        ['Apex Ruler Bastion', '顶峰天帝 巴斯提昂'],
        ['Detonation Mutant Bobalmine', '爆破怪兽 博巴尔麦因'],
        ['Exalting Knight Eafred', '发扬的骑士 埃亚弗雷德'],
        ['Sealed Path', '被封闭的道路'],
        ['Knight of Broadaxe Rafluke', '斧钺的骑士 拉夫尔克'],
        ['Upward Acrobat Marjorie', '高层的杂技师 玛洁莉'],
        ['Conspiring Mutant Admantis', '共谋怪人 增添螳螂'],
        ['Mysterious Rain Spiritualist Zorga', '怪雨的降灵术师 佐尔加'],
        ['Extremist Dragon Velocihazard', '过激龙 涉险伶盗龙'],
        ['Grand Heavenly Sword Alden', '豪仪之天剑 奥尔登'],
        ['Black Tears Husk Dragon', '黑泪之骸龙'],
        ['Grudgeful Hatchet', '憎恨的劈刀'],
        ['Atsushi Toushirou', '厚藤四郎'],
        ['Escort Stealth Dragon Hayashi Kaze', '护卫忍龙 囃子风'],
        ['Phantasma Magician Curtis', '幻想的奇术师 卡提斯'],
        ['Fire Slash Dragon Inferno Sword', '火斩龙 业火之剑'],
        ['Vehement Witch Ramana', '激烈的魔女 拉玛娜'],
        ['Rushing Dragon Steel Dilopho', '急行龙 僵持双冠龙'],
        ['Aurora Battle Princess Agra Rouge', '极光战姬 阿嘉拉·胭脂'],
        ['Aurora Battle Princess Amy Orange', '极光战姬 艾米·橙'],
        ['Aurora Battle Princess Kyanite Blue', '极光战姬 基尔娜·蓝'],
        ['Aurora Battle Princess Seraph Snow', '极光战姬 塞拉斯·白'],
        ['Aurora Battle Princess Treuse Green', '极光战姬 托尔修·绿'],
        ['Aurora Battle Princess Fronte Rose', '极光战姬 芙珑特·玫'],
        ['Aurora Battle Princess Risatt Pink', '极光战姬 莉莎特·粉'],
        ['Aurora Battle Princess Lourus Yellow', '极光战姬 露露丝·黄'],
        ['Aurora Battle Princess Ruby Red', '极光战姬 露比·红'],
        ['Polar Cold Monster Drumler', '极冷怪兽 多拉姆拉'],
        ['Inheritance Maiden Hendrina', '继承的少女 亨德莉娜'],
        ['Kashuu Kiyomitsu Kiwame', '加州清光 极'],
        ['Kashuu Kiyomitsu Toku', '加州清光 特'],
        ['Kashuu Kiyomitsu Sentou', '加州清光 战斗'],
        ['Kashuu Kiyomitsu Shinken Hissatsu', '加州清光 真剑必杀'],
        ['Kashuu Kiyomitsu', '加州清光'],
        ['Imanotsurugi', '今剑'],
        ['Cardinal Noid Cubisia', '柩机之兵 丘比吉亚'],
        ['Cardinal Noid Routis', '柩机之兵 卢奇斯'],
        ['Cardinal Draco Aeblood', '柩机之龙 埃布拉德'],
        ['Cardinal Draco Barbizonde', '柩机之龙 巴比宗德'],
        ['Cardinal Deus Orfist', '柩机之神 奥菲斯特'],
        ['Cardinal Fang Phovi', '柩机之兽 弗维'],
        ['Cardinal Fang Fulgrus', '柩机之兽 弗格尔斯'],
        ['Cardinal Prima Nabilem', '柩机之姬 娜比雷姆'],
        ['Lifesaving Angel Kurabiel', '救命天使 库拉比耶尔'],
        ['Craggy Beast Girgrand', '巨岩怪兽 基尔古兰德'],
        ['Spiritual King of Determination Olbaria', '决意的精灵王 奥尔巴利亚'],
        ['Remission Sword Phanuel', '宽解之太刀 珐努耶尔'],
        ['Tearful Malice', '泪流之恶意'],
        ['Time-fissuring Fist Colossus', '烈震空拳的时空巨兵'],
        ['Spiritual Body Condensation', '灵体凝缩'],
        ['Hexaorb Sorceress', '六角宝珠的女魔术师'],
        ['Midare Toushirou', '乱藤四郎'],
        ['Dream Nibbling', '食梦灵'],
        ['Nakigitsune', '鸣狐'],
        ['Burn Bright Pure Prayers', '清澈的祈祷啊,旺盛燃烧吧'],
        ['In the Darkness Nobody Knows', '于无人知晓的黑暗之中'],
        ['Stealth Dragon Jaengoku', '忍龙 邪炎狱'],
        ['Stealth Dragon Tensha Stead', '忍龙 转写替代'],
        ['Stealth Dragon Hadou Shugen', '忍龙 霸道修验'],
        ['Stealth Fiend Shigamanago', '忍妖 凌汛爱子'],
        ['Light Dragon Deity of Honors Amartinoa', '荣典之光龙神 诺亚圣盾'],
        ['Soulful Wild Master Megan', '入魂的操兽师 梅甘'],
        ['Tri Connect Sorceress', '三角联想的女魔术师'],
        ['Gunning of Dust Storm Nigel', '沙尘之枪击 奈结尔'],
        ['Double Gun of Dust Storm Bart', '沙尘之双枪 巴特'],
        ['Cataclysmic Bullet of Dust Storm Randor', '沙尘之凶弹 兰多尔'],
        ['Heavy Artillery of Dust Storm Eugene', '沙尘之重炮 尤金'],
        ['Abyss Temptation', '深渊引诱使'],
        ['The Hour of Holy Judgement Cometh', '圣裁之刻,来临'],
        ['Ishikirimaru', '石切丸'],
        ['Call to the Beasts', '呼唤兽之声'],
        ['Sylvan Horned Beast Agleo', '树角兽 阿雷伊欧'],
        ['Sylvan Horned Beast Valin', '树角兽 婆黎'],
        ['Sylvan Horned Beast Charis', '树角兽 卡利斯'],
        ['Sylvan Horned Beast Giunosla', '树角兽 丘诺斯拉'],
        ['Sylvan Horned Beast Jackalope', '树角兽 加卡洛普'],
        ['Sylvan Horned Beast Zlatorog', '树角兽 扎拉托洛格'],
        ['Sylvan Horned Beast Dooger', '树角兽 杜伽'],
        ['Sylvan Horned Beast Polatter', '树角兽 珀拉塔'],
        ['Sylvan Horned Beast Lattice', '树角兽 拉提斯'],
        ['Sylvan Horned Beast Lotte', '树角兽 罗特'],
        ['Sylvan Horned Beast King Magnolia', '树角兽王 马格诺利亚'],
        ['Tier Square Sorceress', '四角重层的女魔术师'],
        ['Knight of Heavenly Hammer Gurgant', '天锤的骑士 古尔坎特'],
        ['Knight of Heavenly Wind Vachel', '天风的剑士 维切尔'],
        ['Knight of Heavenly Bows Base', '天弓的骑士 贝斯'],
        ['Knight of Heavenly Pierce Gallus', '天贯的骑士 加尔斯'],
        ['Source Dragon Deity of Blessings Blessfavor', '天惠之源龙王 恩宠吐息'],
        ['Knight of Heavenly Sword Fort', '天剑的骑士 福特'],
        ['Knight of Heavenly Rend Lif', '天裂的骑士 利弗'],
        ['Chakrabarthi Divine Dragon Nirvana', '天轮圣龙 涅槃'],
        ['Knight of Heavenly Spear Rooks', '天枪的骑士 勒克斯'],
        ['Healer of Heavenly Staff Arshes', '天杖的治疗师 阿谢丝'],
        ['Stealth Rogue of Iron Blade Oshikuni', '铁刀的忍鬼 推国'],
        ['Iron Ball Dragon Ankybowler', '铁球龙 投球甲龙'],
        ['Penetrate Dragon Tribash', '突贯龙 猛击三角龙'],
        ['Elegy Pixy', '挽歌的妖精'],
        ['Star Dragon Deity of Infinitude Eldobreath', '无穷之星龙帝 古老星昴'],
        ['Gokotai', '五虎退'],
        ['Pentagleam Sorceress', '五角闪光的女魔术师'],
        ['Fighting Dragon Goldog Dragon', '武斗龙 金斗具龙'],
        ['Hollowing Moonlit Night', '虚无之月夜'],
        ['Blaze Fist Monk Nikko', '焰之拳僧 日光'],
        ['Blaze Maiden Zonne', '焰之巫女 宗妮'],
        ['Blaze Maiden Rino', '焰之巫女 莉诺'],
        ['Blaze Maiden Reiyu', '焰之巫女 蕾尤'],
        ['Blaze Maiden Rona', '焰之巫女 萝娜'],
        ['Blaze Staff Monk Cho Kuu Sha', '焰之杖僧 直射'],
        ['Causality Goes Crazy as I Will It', '狂乱吧因果,遵循我的意志'],
        ['Galaxy Central Prison Galactolus', '银河中央监狱 银河托管所'],
        ['Shadow Bow Archer, Lisana', '影弓的射手 莉萨娜'],
        ['Knight of Friendship Cyrus', '友情的骑士 塞伊拉斯'],
        ['Circuling Sorceress', '圆环的女魔术师'],
        ['Hades Dragon Deity of Resentment Gallmageheld', '怨恨之冥龙神 食尸古贤'],
        ['Rancor Chain', '怨念锁'],
        ['Hopeful Maiden Alejandra', '意愿的少女 亚丽杭德拉'],
        ['Dragon Deity King of Resurgence Dragveda', '再起之龙神王 龙魂吠陀'],
        ['Seizing Slash Mutant Bruslash', '斩获怪人 牛力斩击'],
        ['Knight of War Damage Fosado', '战祸的骑士 弗萨德'],
        ['Actual Analyst Kokabiel', '真相解读 科卡比尔'],
        ['Downswing of Sword of Judgement', '挥起的裁决之剑'],
        ['Stealth Rogue of Strife Fudoumaru', '争斗的忍鬼 不动丸'],
        ['Astute Noble Eddga', '智虑的贵公子 埃德加尔'],
        ['Master of Gravity Baromagnes', '重力的支配者 磁力重压'],
        ['Cursed Souls Squirming in Agony', '受诅咒之魂在痛苦挣扎'],
        ['Gearoid', '齿轮改造体'],
        ['Gear Colossus', '齿轮巨兵'],
        ['Gear Dragon', '齿轮龙'],
        ['Touken Danshi - Uchigatana', '刀剑男士-打刀'],
        ['Touken Danshi - Ootachi', '刀剑男士-大太刀'],
        ['Touken Danshi - Tantou', '刀剑男士-短刀'],
        ['Touken Danshi - Wakizashi', '刀剑男士-胁差'],
        ['Cyberoid', '电子改造体'],
        ['Cyber Dragon', '电子龙'],
        ['Cyber Golem', '电子魔像'],
        ['Cyber Beast', '电子兽'],
        ['Cyber Fairy', '电子妖精'],
        ['Demon', '恶魔'],
        ['High Beast', '高等兽'],
        ['Skeleton', '骨骸'],
        ['Chimera', '合成兽'],
        ['Talisman', '护身符'],
        ['Zombie', '僵尸'],
        ['Elf', '精灵'],
        ['Space Dragon', '空间龙'],
        ['Dinodragon', '恐暴龙'],
        ['Insect', '昆虫'],
        ['Thunder Dragon', '雷龙'],
        ['Tear Dragon', '泪龙'],
        ['Plasma Dragon', '流电龙'],
        ['Succubus', '女魅魔'],
        ['Human', '人类'],
        ['Abyss Dragon', '深渊龙'],
        ['Angel', '天使'],
        ['Alien', '外星人'],
        ['Flame Dragon', '炎龙'],
        ['Wild Dragon', '野性龙'],
        ['Shadow Army', '夜影兵'],
        ['Ghost', '幽灵'],
        ['Cosmo Dragon', '宇宙龙'],
        ['Elemental', '元素精灵'],
        ['Battleroid', '战斗机器人'],
        ['Bioroid', '植培种'],
        ['Nature Dragon', '自然龙'],
        ['Workeroid', '作业机器人'],
        ['Waiting for your opponent', '等待你的对手'],
        ['Choose the cards to replace.', '选择要替换的卡。'],
        ['Waiting for your opponent', '等待你的对手'],
        ['Exit Game', '退出游戏'],
        ['To Main', '主要阶段'],
        ['Add GC', '防御'],
        ['Confirm', '确认'],
        ['To Battle', '战斗阶段'],
        ['End Turn', '回合结束'],
        ['Prison Break', '越狱'],
        ['Cost', '费用'],
        ['Rest', '横置'],
        ['Discard', '丢弃手牌'],
        ['Attack', '攻击'],
        ['Enemy Left Rearguard Power', '对手左侧后防者力量值'],
        ['Enemy Right Rearguard Power', '对手右侧后防者力量值'],
        ['VS Vanguard Power', '你的先导者力量值'],
        ['Activate Skill', '使用技能'],
        ['Soulblast', '灵魂爆发'],
        ['Soulblast', '灵魂爆发'],
        ['cb and sb', '计数爆发和灵魂爆发'],
        ['Counterblast', '计数爆发'],
        ['Imprison', '收容'],
        ['BATTLE', '战斗'],
        ['Interceptot', '拦截'],
        ['for Perfect Guard', '使用完全防御'],
        ['Give 100 Million to an Ally', '给单位加1亿力量值'],
        ['You beat', '你击败了'],
        ['Game Modes', '游戏模式'],
        ['Normal', '普通'],
        ['Back', '返回'],
        ['Matching', '匹配中'],
        ['You completed a match', '你完成了对战'],
        ['Create New Card', '创建新卡'],
        ['Create a new card of type Unit for this game.', '为此游戏创建一张新的单位卡'],
        ['Create a new card of type Order for this game.', '为此游戏创建一张新的指令卡'],
        ['Create a new card of type Trigger for this game.', '为此游戏创建一张新的触发卡'],
        ['Create a new card of type OverTrigger for this game.', '为此游戏创建一张新的超触发卡'],
        ['Create a new card of type OverTrigger Order for this game.', '为此游戏创建一张新的超触发指令卡'],
        ['Please login first', '请先登录您内'],
        ['Click on this box to dismiss', '单击此框可取消'],
        ['Are you sure', '你确定吗'],
        ['Did you mean', '你想使用'],
        ['About Dulst', '关于Dulst'],
        ['About', '关于'],
        ['Contact', '联系方式'],
        ['Terms', '用户协议'],
        ['Privacy', '隐私策略'],
        ['More...', '更多...'],
        ['Social Media', '社交媒体'],
        ['Twitter', '推特'],
        ['Leaderboard', '排行榜'],
        ['Player Rankings', '玩家排名'],
        ['Play Cardfight!! Vanguard now!!', '立即游玩卡片战斗先导者！！'],
        ['Play now for free', '现在免费游玩（注册）'],
        ['Play Now', '开始游戏'],
        ['Play', '匹配'],
        ['View All Cards', '查看所有卡片'],
        ['Home', '首页'],
        ['Cards List', '卡片列表'],
        ['Community', '论坛'],
        ['Market', '商店'],
        ['Game Chat', '游戏聊天'],
        ['Dulst Chat', 'Dulst聊天'],
        ['Sign Up', '注册'],
        ['Login', '登陆'],
        ['Username or Email:', '用户名或邮箱：'],
        ['Email:', '邮箱：'],
        ['Username:', '用户名：'],
        ['Verify Password:', '再打一遍密码：'],
        ['Password:', '密码：'],
        ['Register', '注册'],
        ['Forgot Password?', '找回密码'],
        ['Your Games', '你玩过的游戏'],
        ['Options', '选项'],
        ['Logout', '退出登录'],
        ['Account Settings', '帐户设置'],
        ['Dulst Profile', 'Dulst个人资料'],
        ['actives', '在线人数'],
        ['Profile', '简介'],
        ['Game profile', '游戏记录'],
        ['Card Packs', '卡包'],
        ['Buy for ', '购买并花费：'],
        ['overPriced', '定价过高'],
        ['Contains overTriggers but priced to be in theme', '包含超触发,但是价格我说了算'],
        ['Genesis of the Five Greats', '五大世纪之黎明'],
        ['The new Vanguard raises the curtains here', '全新的先导者于此拉开了序幕'],
        ['A Brush with the Legends', '与传说的邂逅'],
        ['The battle will be further \'intensified\'', '战斗将进一步"激化"'],
        ['A collaborative booster between Cardfight!! Vanguard and the online browser game Touken Ranbu.', '卡片战斗先导者与网页游戏刀剑乱舞之间的联动。'],
        ['Festival Collection', '节日典藏包'],
        ['Only contains 3 cards, all RRR!', '仅仅包含3张卡,全部都是RRR！'],
        ['You cannot afford this', '您买不起QvQ'],
        ['View Article', '查看文章'],
        ['News', '新闻'],
        ['Strategy', '攻略'],
        ['Card Requests', '卡片问题'],
        ['Issue', '重要议题'],
        ['Suggestion', '建议'],
        ['Bug', '故障'],
        ['Balance', '平衡'],
        ['Etc', '其他'],
        ['Forums', '论坛'],
        ['Wiki & Docs & Help', '维基、文档和帮助'],
        ['Wiki', '维基'],
        ['All', '全部'],
        ['Discuss this page', '讨论此页'],
        ['cardideas', '卡牌创意'],
        ['Card Ideas', '卡牌创意'],
        ['Suggest Your Cards', '推荐你的卡牌游戏'],
        ['Create New Game', '创造新游戏'],
        ['Active Offers', '积极提议'],
        ['Offers In Revision', '修订版本'],
        ['Edit Mode', '编辑模式'],
        ['Edit', '编辑'],
        ['View full thread', '查看完整过程'],
        ['Delete', '删除'],
        ['Body', '正文'],
        ['Submit Post', '提交帖子'],
        ['My decks', '我的卡片'],
        ['My Decks', '我的卡片'],
        ['Switch Deck', '切换卡组'],
        ['New Deck', '新建卡组'],
        ['Cards in this Set', '点这里分解卡片'],
        ['Cards', '卡片'],
        ['Unit', '单位'],
        ['OverTrigger Order', '超触发指令'],
        ['Order', '指令'],
        ['OverTrigger', '超触发'],
        ['Trigger', '触发'],
        ['version', '版本'],
        ['Crafting With Sets', '手动分解'],
        ['Level 1', '等级1'],
        ['Points', '点数'],
        ['Set Reward', '分解报酬'],
        ['Sets', '分解'],
        ['Coin Converter', '硬币转换器'],
        ['Converter', '转换器'],
        ['Any', '任何'],
        ['Insert a', '放入一张'],
        ['Time left: less than 1 minute', '剩余时间：不到1分钟'],
        ['coins', '硬币'],
        ['Coins', '硬币'],
        ['Collectible', '收藏'],
        ['Game Rule', '游戏规则'],
        ['Sort by ', '排序依据：'],
        ['Updated Date', '发布日期'],
        ['Name', '卡名'],
        ['Rarity', '稀有度'],
        ['Have Card', '添加卡片'],
        ['power', '力量'],
        ['shield', '护盾'],
        ['grade', '等级'],
        ['critical', '暴击'],
        ['nation', '国家'],
        ['counterblasted', '计数爆发'],
        ['personaride', '人格ride'],
        ['triggertype', '触发种类'],
        ['Be careful! This can eat TRIAL DECK cards!', '小心！这个能吃【初始卡组】的牌！'],
        ['Insert your least rare excess card.', '插入你最不罕见的多余卡片。'],
        ['Gallery', '画廊'],
        ['OverDulst', '超限舞装'],
        ['Ranked', '排位'],
        ['Custom Lobby', '定制大厅'],
        ['ACT', '起'],
        ['CONT', '永'],
        ['AUTO', '自'],
        ['Blitz', '闪现'],
        ['Blit', '闪现'],
        ['Set', '设置'],
        ['Prison', '监狱'],
        ['Shield', '盾护'],
        ['this unit', '这个单位'],
        ['If it is', '如果是'],
        ['if it', '如果它'],
        ['this gets', '这个单位获得'],
        ['get', '获得'],
        ['Boost', '支援'],
        ['Power', '力量'],
        ['state hits', '状态并击中时'],
        ['state', '状态'],
        ['two rear-guards', '2张后防者'],
        ['The Collection', '全部收藏'],
        ['Collection', '收藏'],
        ['Holy Dragon', '天轮圣龙'],
        ['Tyrant Tiger', '暴虐之虎'],
        ['Apex Ruler', '顶峰天帝'],
        ['Sylvan King', '树角兽王'],
        ['Aurora Valkyrie', '极光战姬'],
        ['Dark States', '暗邦'],
        ['Brandt Gate', '布兰特之门'],
        ['Touken Ranbu', '刀剑乱舞'],
        ['Stoicheia', '基元'],
        ['Dragon Empire', '龙族帝国'],
        ['Keter Sanctuary', '王冠圣域'],
        ['Rule', '规则'],
        ['Intercept', '截击'],
        ['token', '衍生物'],
        ['Promo Voucher', 'Pr兑换券'],
        ['call a', 'CALL一个'],
        ['ability', '能力'],
        ['drive', '判定'],
        ['if you', '如果你'],
        ['another rear-guard', '你其他的1张后防者'],
        ['OKAY', '确认'],
        ['instead,', '的话,'],
        ['Overlord', '帝王'],
        ['Diabolos', '魔惧会'],
        ['originalDress', '舞装源'],

    ])

    replaceText(document.body)

    const bodyObserver = new MutationObserver(mutations => {
        mutations.forEach(mutation => {
            mutation.addedNodes.forEach(addedNode => replaceText(addedNode))
        })
    })
    bodyObserver.observe(document.body, { childList: true, subtree: true })

    function replaceText(node) {
        nodeForEach(node).forEach(htmlnode => {
            i18n.forEach((value, index) => {
                const textReg = new RegExp(index, 'g')
                if (htmlnode instanceof Text ) {
                    htmlnode.nodeValue = htmlnode.nodeValue.replace(textReg, value)
                }
                else if (htmlnode instanceof HTMLInputElement ) {
                    htmlnode.value = htmlnode.value.replace(textReg, value)
                }
            })
        })
    }

    function nodeForEach(node) {
        const list = []
        if (node.childNodes.length === 0) list.push(node)
        else {
            node.childNodes.forEach(child => {
                if (child.childNodes.length === 0) list.push(child)
                else list.push(...nodeForEach(child))
            })
        }
        return list
    }
})();